<SCRIPT language=JavaScript src="java.js"></SCRIPT>
<SCRIPT language=JavaScript type=text/javascript>
		 <!-- JavaScript code to remove dotted lines from around links in IE.
		    function ExplorerFix() {
			    for (a in document.links) document.links[a].onfocus = 
			    document.links[a].blur;
		    }
			
		    if (document.all) {
			    document.onmousedown = ExplorerFix;
		    }
			// -->
		</SCRIPT>

<A name=top></A> 
<table cellspacing=0 cellpadding=0  border=0 width="150">
  <tbody>
    <tr> 
	  <td width="1"></td>
      <td valign=center width=160 class="box" align="center">
	  <br> 
	  <br>
	  <br>
	  <a class="boxlink" href="default.asp">
	  	<center>
			&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;~&nbsp;Home&nbsp;~&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
		</center>
	  </a><br>
	  <a class="boxlink" href="aboutus.asp">
	  	<center>
			&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;~&nbsp;About Us&nbsp;~&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
		</center>
	  </a><br>
	  <a href="location.asp" class="boxlink">
	  	<center>
			&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;~&nbsp;Location&nbsp;~&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
		</center>
	  </a><br>
	  <a href="product_menu.asp" class="boxlink">
	  	<center>
			&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;~&nbsp;Products&nbsp;~&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
		</center>
	  </a><br>
	  <a href="login.asp" class="boxlink">
	  	<center>
			&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;~&nbsp;Order Form&nbsp;~&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
		</center>
	  </a><br>
	  <a href="contactus.asp" class="boxlink">
	  	<center>
			&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;~&nbsp;Contact Us&nbsp;~&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
		</center>
	  </a><br>
	  <a href="enquiry.asp" class="boxlink">
	  	<center>&nbsp;&nbsp;~&nbsp;Product Enquiry&nbsp;~&nbsp;&nbsp;</center>
	  </a>
	  <br>
		 <a class="boxlink" href="login.asp">
	  	<center>
			&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;~&nbsp;Log In&nbsp;~&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
		</center>
	  </a><br>
		  	  </td>
    </tr>
  </tbody>
</table>
