
<LINK href="main.css" type=text/css rel=STYLESHEET>
<SCRIPT language="javascript" src="Js/Time_Fun.js"></SCRIPT>
<DIV id=Layer1 style="LEFT: 375px; POSITION: absolute; TOP: 7px; VISIBILITY: visible; Z-INDEX:7;width:300px"></DIV>
<TABLE cellSpacing=0 cellPadding=0 width="100%" border=0>
  
  <TR>
    <TD width="100%" bgColor=#004584><IMG height=6 alt="" 
      src="images/spacer.gif" width=525 border=0></TD>
    <TD vAlign=top width=76 rowSpan=2><IMG height=76 alt=Graphic 
      src="images/home_topnav_graphic_01.gif" width=227 border=0></TD></TR>
  <TR>
<TD WIDTH='100%' HEIGHT='69'><A HREF='/home.html'><IMG SRC='images/logo.gif'  BORDER='0'></A>

</TD>
</TR>
  <TR>
    <TD width="100%" bgColor=#004584 height=21>
      <TABLE cellSpacing=0 cellPadding=0 border=0>
        <TR>
          <TD width=12 height=20></TD>
          <TD noWrap height=20><A class=primaryNavLink href="default.asp">Home</A></TD>
          <TD width=5 height=20><IMG height=20 alt="" src="images/spacer.gif" width=5 border=0></TD>
          <TD vAlign=bottom width=1 height=20><IMG height=20 alt="" 
            src="images/topnav_vertical_line.gif" width=1 border=0></TD>
          <TD width=5 height=20><IMG height=20 alt="" 
            src="images/spacer.gif" width=5 border=0></TD>
          <TD noWrap height=20><A class=primaryNavLink 
            href="product.asp">Products</A></TD>
          <TD width=5 height=20><IMG height=20 alt="" 
            src="images/spacer.gif" width=5 border=0></TD>
          <TD vAlign=bottom width=1 height=20><IMG height=20 alt="" 
            src="images/topnav_vertical_line.gif" width=1 border=0></TD>
          <TD width=5 height=20><IMG height=20 alt="" 
            src="images/spacer.gif" width=5 border=0></TD>
          <TD noWrap height=20><A class=primaryNavLink 
            href="features.asp">Features</A></TD>
          <TD width=5 height=20><IMG height=20 alt="" 
            src="images/spacer.gif" width=5 border=0></TD>
          <TD vAlign=bottom width=1 height=20><IMG height=20 alt="" 
            src="images/topnav_vertical_line.gif" width=1 border=0></TD>
          <TD width=5 height=20><IMG height=20 alt="" 
            src="images/spacer.gif" width=5 border=0></TD>
          <TD noWrap height=20><A class=primaryNavLink 
            href="Services.asp">Services</A></TD>
          <TD width=5 height=20><IMG height=20 alt="" 
            src="images/spacer.gif" width=5 border=0></TD>
          <TD vAlign=bottom width=1 height=20><IMG height=20 alt="" 
            src="images/topnav_vertical_line.gif" width=1 border=0></TD>
          <TD width=5 height=20><IMG height=20 alt="" 
            src="images/spacer.gif" width=5 border=0></TD>
            <TD noWrap height=20><A class=primaryNavLink 
            href="Track_order.asp">Track Order
           </A></TD>
          <TD width=5 height=20><IMG height=20 alt="" 
            src="images/spacer.gif" width=5 border=0></TD>
          <TD vAlign=bottom width=1 height=20><IMG height=20 alt="" 
            src="images/topnav_vertical_line.gif" width=1 border=0></TD>
          <TD width=5 height=20><IMG height=20 alt="" 
            src="images/spacer.gif" width=5 border=0></TD>
			<TD noWrap height=20><A class=primaryNavLink 
            href="Advanced_Search.asp">Search</A></TD>
          <TD width=5 height=20><IMG height=20 alt="" 
            src="images/spacer.gif" width=5 border=0></TD>
          <TD vAlign=bottom width=1 height=20><IMG height=20 alt="" 
            src="images/topnav_vertical_line.gif" width=1 border=0></TD>
          <TD width=5 height=20><IMG height=20 alt="" 
            src="images/spacer.gif" width=5 border=0></TD>
          <TD noWrap height=20><A class=primaryNavLink 
            href="contactus.asp">Contact us</A></TD>
          <TD width=5 height=20><IMG height=20 alt="" 
            src="images/spacer.gif" width=5 border=0></TD>
          <TD vAlign=bottom width=1 height=20><IMG height=20 alt="" 
            src="images/topnav_vertical_line.gif" width=1 
        border=0></TD>
           <MM:BeginLock translatorClass="MM_SSI" type="ssi_comment" orig="%3C!-- #include file=%22myheader.inc%22 --%3E" fileRef="myheader.inc" depFiles="file:///E|/Projects/Rug/inc/myheader.inc"><!-- Dynamic title for coustomer -->
<% 
           if session("custid") <> "" then
%>
           <TD width=5 height=20><IMG height=20 alt="" 
            src="images/spacer.gif" width=5 border=0></TD>
          <TD noWrap height=20><A class=primaryNavLink 
            href="customer_view.asp">My profile
            </A></TD>
          <TD width=5 height=20><IMG height=20 alt="" 
            src="images/spacer.gif" width=5 border=0></TD>
          <TD vAlign=bottom width=1 height=20><IMG height=20 alt="" 
            src="images/topnav_vertical_line.gif" width=1 border=0></TD>
          <TD width=5 height=20><IMG height=20 alt="" 
            src="images/spacer.gif" width=5 border=0></TD>
          <TD noWrap height=20><A class=primaryNavLink 
            href="userlogout.asp">Logout</A></TD>
          <TD width=5 height=20><IMG height=20 alt="" 
            src="images/spacer.gif" width=5 border=0></TD>
          <TD vAlign=bottom width=1 height=20><IMG height=20 alt="" 
            src="images/topnav_vertical_line.gif" width=1 
        border=0></TD>
<% end if %>
<MM:EndLock>
</TR>

</TABLE>
</TD>

    <TD width=76 bgColor=#4d7da9 height=21>
      <TABLE cellSpacing=0 cellPadding=0 width=217 border=0>
        
        <TR>
          <TD width=76><IMG height=21 alt="" 
            src="images/products_topnav_graphic_02.gif" width=76 
          border=0></TD>
          <TD width=20><SPACER width="20" type="block" height="5"></TD>
          <TD class=smbodytext noWrap width=111>
		  <B><FONT color=#ffffff>
<!--Display today's date-->

<SCRIPT  language="JavaScript">
displaytime()
</SCRIPT>
</FONT></B>
</TD>
<TD width=10>
<SPACER width="4" type="block" height="5">
<SPACER width="10" type="block" height="1">
</TD></TR>
</TABLE>
</TD>
</TR>
</TABLE>
<MM:BeginLock translatorClass="MM_SSI" type="ssi_comment" orig="%3C!-- #include file=%22banner_header.asp%22 --%3E" fileRef="banner_header.asp" depFiles="file:///C|/Inetpub/wwwroot/rug/inc/banner_header.asp"><MM:BeginLock translatorClass="MM_SSI" type="ssi_comment" orig="%3C!-- #include file=%22../inc/database.asp%22 --%3E" fileRef="../inc/database.asp" depFiles="file:///C|/Inetpub/wwwroot/rug/inc/database.asp"><%
	'Dim constring,UserName,Pwd
	'constring="Provider=SQLOLEDB;Data Source=GMS;User Id=sa;Password=dogdog4;Initial Catalog=rug;"
	'constring="Provider=SQLOLEDB;Data Source=216.250.116.9;User Id=60second;Password=60second;Initial Catalog=networkdb;"
	'set Con=Server.CreateObject("ADODB.Connection")
	'Con.open constring
%><MM:EndLock>
<%
set ba=server.CreateObject("adodb.recordset")
bname="home"
st="Y"
sql="select bannerdescription from R_Banneradmin where upper(banner_name)='"& ucase(bname) &"' and activestatus='"& st &"'"
ba.open sql,con
if not ba.eof Then
  va=ba("bannerdescription")
else
  va="Wel Come"
end if
ba.close
con.close

%>

<input name="bvalue" type="hidden" value="<% =va %>">
<MM:EndLock>
<SCRIPT language=javascript src="JS/Banner_Script.js"></script>
<script language="javascript">
var tt;
tt=document.getElementById("bvalue");
   funvalue(tt.value);
   showtop();
</script>


